import { Bot, BotCategory, OutbidNotification } from '../types';

export const INITIAL_BOTS: Bot[] = [
  {
    id: 'bot-1',
    telegram_username: 'TikGrab_Bot',
    bot_name: 'TikGrab — Download Video TikTok HD Tanpa Watermark',
    avatar_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    description: 'Download video TikTok, IG Reels, Twitter/X, dan YouTube Shorts kualitas HD tanpa watermark dalam hitungan detik.',
    category: 'DOWNLOADER',
    custom_tagline: 'Bot download video tercepat & terlengkap di Telegram',
    total_bid_amount: 1000000,
    contact_handle: '@tikgrab_support',
    is_verified: true,
    is_online: true,
    daily_clicks: 1420,
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'bot-2',
    telegram_username: 'PintarAI_Bot',
    bot_name: 'PintarAI — Asisten GPT-4o & Claude 3.5 Sonnet Bahasa Indo',
    avatar_url: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=200&auto=format&fit=crop&q=80',
    description: 'Tanya apapun dalam Bahasa Indonesia, bikin skripsi, coding, edit foto AI, dan ringkas PDF langsung di Telegram.',
    category: 'AI',
    custom_tagline: 'AI tercerdas untuk mahasiswa & pekerja profesional',
    total_bid_amount: 500000,
    contact_handle: '@pintarai_dev',
    is_verified: true,
    is_online: true,
    daily_clicks: 3946,
    created_at: '2026-08-24T14:30:00Z',
  },
  {
    id: 'bot-3',
    telegram_username: 'AnonChatIndoBot',
    bot_name: 'AnonChat Indo — Cari Teman Curhat & Ngobrol Anonim',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    description: 'Temukan teman ngobrol acak se-Indonesia tanpa tukar nomor hp. Aman, seru, dan ada filter gender & lokasi.',
    category: 'ANON_CHAT',
    custom_tagline: 'Komunitas anonim terbesar dengan 500rb+ pengguna aktif',
    total_bid_amount: 300000,
    contact_handle: '@anonchat_admin',
    is_verified: true,
    is_online: true,
    daily_clicks: 555,
    created_at: '2026-08-26T08:00:00Z',
  },
  {
    id: 'bot-4',
    telegram_username: 'TopUpGameBot',
    bot_name: 'TopUp Kilat — Voucher MLBB, FF, Genshin & Steam Otomatis',
    avatar_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=200&auto=format&fit=crop&q=80',
    description: 'Topup game termurah open 24 jam dengan QRIS otomatis detik itu juga masuk. Garansi 100% legal dan terpercaya.',
    category: 'STORE',
    custom_tagline: 'Harga reseller termurah untuk semua gamer Indo',
    total_bid_amount: 255764,
    contact_handle: '@topupkilat_cs',
    is_verified: true,
    is_online: true,
    daily_clicks: 164,
    created_at: '2026-08-25T11:20:00Z',
  },
  {
    id: 'bot-5',
    telegram_username: 'OrkataBot',
    bot_name: 'Orkata.co — Build Chatbot AI Otomatis untuk Bisnis & Olshop',
    avatar_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&auto=format&fit=crop&q=80',
    description: 'Buat chatbot AI pintar yang bisa jawab FAQ, cek stok toko, terima order, dan forward ke CS manusia.',
    category: 'TOOLS',
    custom_tagline: 'Solusi automasi CS nomor 1 untuk bisnis online',
    total_bid_amount: 255763,
    contact_handle: '@orkata_help',
    is_verified: false,
    is_online: true,
    daily_clicks: 244,
    created_at: '2026-08-25T16:45:00Z',
  },
  {
    id: 'bot-6',
    telegram_username: 'MindfulDayBot',
    bot_name: 'MindfulDay — Tracker Produktivitas, Habit & Pomodoro',
    avatar_url: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=200&auto=format&fit=crop&q=80',
    description: 'Pengingat to-do harian, timer pomodoro cerdas, dan jurnal motivasi untuk kamu yang ingin lebih produktif.',
    category: 'TOOLS',
    custom_tagline: 'Teman setia mencapai target harianmu',
    total_bid_amount: 250000,
    contact_handle: '@mindful_creator',
    is_verified: false,
    is_online: true,
    daily_clicks: 365,
    created_at: '2026-08-24T09:15:00Z',
  },
  {
    id: 'bot-7',
    telegram_username: 'KlipAjaBot',
    bot_name: 'KlipAja.id — AI Ubah Video YouTube Jadi Klip Viral TikTok/Reels',
    avatar_url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=200&auto=format&fit=crop&q=80',
    description: 'Paste link video panjang, AI otomatis memotong bagian terbaik lengkap dengan subtitle otomatis ala MrBeast!',
    category: 'AI',
    custom_tagline: 'Senjata rahasia para content creator affiliate',
    total_bid_amount: 123123,
    contact_handle: '@klipaja_cs',
    is_verified: true,
    is_online: true,
    daily_clicks: 722,
    created_at: '2026-08-25T19:00:00Z',
  },
  {
    id: 'bot-8',
    telegram_username: 'CekMotorAIBot',
    bot_name: 'CekMotor — Estimasi Harga Pasar Motor Bekas via AI',
    avatar_url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=200&auto=format&fit=crop&q=80',
    description: 'Kirim foto atau tipe motor, AI langsung kalkulasi taksiran harga wajar jual/beli berdasarkan data dealer terpercaya.',
    category: 'TOOLS',
    custom_tagline: 'Panduan wajib sebelum jual-beli motor second',
    total_bid_amount: 123000,
    contact_handle: '@cekmotor_id',
    is_verified: false,
    is_online: true,
    daily_clicks: 152,
    created_at: '2026-08-24T12:00:00Z',
  },
  {
    id: 'bot-9',
    telegram_username: 'ClarityFocusBot',
    bot_name: 'Clarity — Morning Brain Dump & Daily Clarity Bot',
    avatar_url: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=200&auto=format&fit=crop&q=80',
    description: 'Bantu kamu menjernihkan pikiran di pagi hari, menyusun 3 prioritas terpenting, dan evaluasi sore hari.',
    category: 'TOOLS',
    custom_tagline: 'Kurangi overthinking, tingkatkan fokus kerja',
    total_bid_amount: 115000,
    contact_handle: '@clarity_bot_dev',
    is_verified: false,
    is_online: true,
    daily_clicks: 269,
    created_at: '2026-08-23T15:30:00Z',
  },
  {
    id: 'bot-10',
    telegram_username: 'KaloriTrackerBot',
    bot_name: 'Kalori Tracker AI — Foto Makanan & Hitung Nutrisi Otomatis',
    avatar_url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=200&auto=format&fit=crop&q=80',
    description: 'Cukup foto piring makananmu atau ketik "nasi padang rendang", AI langsung hitung kalori, protein, lemak & karbo.',
    category: 'AI',
    custom_tagline: 'Diet sehat anti ribet langsung dari Telegram',
    total_bid_amount: 111111,
    contact_handle: '@kalori_support',
    is_verified: true,
    is_online: true,
    daily_clicks: 248,
    created_at: '2026-08-23T18:00:00Z',
  },
  {
    id: 'bot-11',
    telegram_username: 'TrakteerBot',
    bot_name: 'Trakteer Notifier — Notifikasi Donasi & Saweran Kreator',
    avatar_url: 'https://images.unsplash.com/photo-1579208575657-c595a05383b7?w=200&auto=format&fit=crop&q=80',
    description: 'Terima notifikasi instan saat ada fans yang traktir karya kamu di Trakteer. Kustomisasi pesan suara & ucapan terima kasih.',
    category: 'TOOLS',
    custom_tagline: 'Integrasi wajib kreator konten Indonesia',
    total_bid_amount: 100000,
    contact_handle: '@trakteer_fan',
    is_verified: true,
    is_online: true,
    daily_clicks: 291,
    created_at: '2026-08-23T20:00:00Z',
  },
  {
    id: 'bot-12',
    telegram_username: 'WariskanBot',
    bot_name: 'Wariskan — Kalkulator Waris Syariah & Silsilah Keluarga',
    avatar_url: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=200&auto=format&fit=crop&q=80',
    description: 'Hitung pembagian harta warisan sesuai kaidah Faraidh Islam secara akurat, mudah dipahami, dan dapat file PDF rincian.',
    category: 'TOOLS',
    custom_tagline: 'Kalkulator waris syariah terlengkap & terpercaya',
    total_bid_amount: 88890,
    contact_handle: '@wariskan_cs',
    is_verified: false,
    is_online: true,
    daily_clicks: 171,
    created_at: '2026-08-23T21:15:00Z',
  },
  {
    id: 'bot-13',
    telegram_username: 'DospemAIBot',
    bot_name: 'Dospem.id — Asisten Review Skripsi & Jurnal Ilmiah 24/7',
    avatar_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=200&auto=format&fit=crop&q=80',
    description: 'Bantu bedah bab 1-5, parafrase anti-turnitin, cek typo KBBI, dan cari referensi jurnal bereputasi Scopus/Sinta.',
    category: 'AI',
    custom_tagline: 'Teman setia pejuang skripsi anti revisi',
    total_bid_amount: 88888,
    contact_handle: '@dospem_help',
    is_verified: true,
    is_online: true,
    daily_clicks: 476,
    created_at: '2026-08-23T22:00:00Z',
  },
  {
    id: 'bot-14',
    telegram_username: 'KontaxtaxBot',
    bot_name: 'KonTax — Konsultan Pajak UMKM & Coretax Assistant',
    avatar_url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200&auto=format&fit=crop&q=80',
    description: 'Hitung PPh Final UMKM 0.5%, PPh 21 karyawan, dan panduan pelaporan SPT Tahunan online tanpa pusing istilah pajak.',
    category: 'TOOLS',
    custom_tagline: 'Urus pajak bisnis jadi simpel dan tenang',
    total_bid_amount: 69696,
    contact_handle: '@kontax_admin',
    is_verified: false,
    is_online: true,
    daily_clicks: 611,
    created_at: '2026-08-23T23:30:00Z',
  },
  {
    id: 'bot-15',
    telegram_username: 'CariLeadsBot',
    bot_name: 'CariLeads — Scraper Data Bisnis Google Maps & WA Blast',
    avatar_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=200&auto=format&fit=crop&q=80',
    description: 'Cari ribuan prospek calon pembeli B2B per kota dari GMaps, filter nomor WA valid, dan kirim pesan broadcast terpersonalisasi.',
    category: 'TOOLS',
    custom_tagline: 'Mesin pencetak database prospek otomatis',
    total_bid_amount: 55001,
    contact_handle: '@carileads_help',
    is_verified: false,
    is_online: true,
    daily_clicks: 4300,
    created_at: '2026-08-24T00:30:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: OutbidNotification[] = [
  {
    id: 'notif-1',
    bot_name: 'NgetesTools — Bot Tester API',
    telegram_username: 'ngetestools_bot',
    old_rank: 54,
    new_rank: 1,
    amount_added: 2829,
    timestamp: '2 jam yang lalu',
  },
  {
    id: 'notif-2',
    bot_name: 'Simpul — One Link Bio Telegram',
    telegram_username: 'simpul_bot',
    old_rank: 44,
    new_rank: 2,
    amount_added: 10000,
    timestamp: '5 jam yang lalu',
  },
  {
    id: 'notif-3',
    bot_name: 'Queay — Antrean Resto Otomatis',
    telegram_username: 'queay_bot',
    old_rank: 107,
    new_rank: 3,
    amount_added: 1000,
    timestamp: '7 jam yang lalu',
  },
  {
    id: 'notif-4',
    bot_name: 'DIRO — Bot Polling & Voting Anon',
    telegram_username: 'diro_bot',
    old_rank: 43,
    new_rank: 4,
    amount_added: 10000,
    timestamp: '7 jam yang lalu',
  },
  {
    id: 'notif-5',
    bot_name: 'Lauraisasti AI Photo Generator',
    telegram_username: 'laura_ai_bot',
    old_rank: 66,
    new_rank: 5,
    amount_added: 1001,
    timestamp: '7 jam yang lalu',
  },
  {
    id: 'notif-6',
    bot_name: 'InfoCuanIndo — Bot Sinyal Promo',
    telegram_username: 'infocuan_bot',
    old_rank: 104,
    new_rank: 6,
    amount_added: 1000,
    timestamp: '10 jam yang lalu',
  },
  {
    id: 'notif-7',
    bot_name: 'KontenKit — AI Caption & Hashtag',
    telegram_username: 'kontenkit_bot',
    old_rank: 65,
    new_rank: 7,
    amount_added: 1001,
    timestamp: '11 jam yang lalu',
  },
  {
    id: 'notif-8',
    bot_name: 'Iksae — Catat Keuangan Pribadi',
    telegram_username: 'iksae_bot',
    old_rank: 53,
    new_rank: 8,
    amount_added: 2001,
    timestamp: '11 jam yang lalu',
  },
];
